replicaCount: 1

image:
  repository: ""
  tag: ""

# -- Override the namespace
# @default -- `.Release.Namespace`
namespaceOverride: ""

env: []

global:
  pool: ""
  url: ""
  token: ""
  stack: ""
