on:
  # pull_request:
  #   branches:
  #     - main
  push:
    branches:
      - main
      - feat/actions
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v6

      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terragrunt
          path: live

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: prod
    permissions:
      id-token: write
      contents: read
    env:
      TERRAGRUNT_WORKING_DIRECTORY: terragrunt

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v5
        with:
          name: terragrunt
          path: ${{ env.TERRAGRUNT_WORKING_DIRECTORY }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions
          role-session-name: github-actions

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.0

      - name: Install Terragrunt
        run: |
          curl -Lo terragrunt-bin https://github.com/gruntwork-io/terragrunt/releases/download/v0.96.1/terragrunt_linux_amd64
          chmod +x terragrunt-bin
          sudo mv terragrunt-bin /usr/local/bin/terragrunt

      - name: Get Backend Parameter
        run: |
          BACKEND=$(aws ssm get-parameter \
            --name "/backend" \
            --with-decryption \
            --query "Parameter.Value" \
            --output text)

          echo "BACKEND=$BACKEND" >> $GITHUB_ENV

      - uses: qetza/replacetokens-action@v1
        with:
          sources: |
            variables.auto.tfvars.tmpl => variables.auto.tfvars
          variables: >
            [
              ${{ toJSON(vars) }},
              ${{ toJSON(secrets) }},
              { "SERVICE": "aws-multi-account-agents" },
              { "BACKEND": $BACKEND },
            ]
          token-pattern: custom
          token-prefix: '${'
          token-suffix: '}'
          log-level: debug
          no-telemetry: true
          root: ${{ env.TERRAGRUNT_WORKING_DIRECTORY }}

      - name: Terragrunt Init
        run: terragrunt run --all init
        working-directory: ${{ env.TERRAGRUNT_WORKING_DIRECTORY }}